### PR TITLE
Update to Bootstrap 5.3.1 and interface refresh

### PR DESCRIPTION
**Pull request by LordAro**
Update to newest Bootstrap and redo a load of the interface. Very much WIP and I'm sure people will have Opinions.

Original motivation: jQuery 1.9.1 is really old, and full of security issues. Bootstrap 2.3 is similarly old.

### CODE REVIEW

**Comment by LordAro** [comment]
cc @andythenorth for suitable judgement (and because he did the interface the last time round, even if it was 10 years ago)

**Comment by TrueBrain** [comment]
Opinions is a strong word, but when I look at editing a string, I used to see this:

image

I now see this:

image

That really doesn't look good. In fact, I got a bit lost where to find information in the latter, where the first assists me where to look. Mostly, the smaller textarea is a recipe for disaster :D Maybe there are some easy things we can do here to make the old compatible with the new?

**Comment by TrueBrain** [comment]
Any progress? :)

**Comment by TrueBrain** [comment]
I think it is totally safe to say this is not going to happen anymore.

Especially as we started to rewrite eints into [nile](https://github.com/OpenTTD/nile), nobody should put any additional effort into it.

But I do appreciate you tried :) It is more than most people did over the last few years :D

**Pull request closed without merging**
